sudo: required
services:
    - docker

before_install:
    -docker build -t spanchagnula/react-test -f ./client/Dockerfile.dev ./client 

script:
    - docker run -e CI=true USERNAME/react-test npm test

after_success:
    - docker build -t spanchagnula/multi-client ./client 
    - docker build -t spanchagnula/multi-nginx ./nginx 
    - docker build -t spanchagnula/multi-server ./server
    - docker build -t spanchagnula/multi-worker ./worker 

    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    
    #    Take those images and push them to docker hub
    - docker push spanchagnula/multi-client 
    - docker push spanchagnula/multi-nginx
    - docker push spanchagnula/multi-server
    - docker push spanchagnula/multi-worker
